### ISSUE TITLE
Stuck on boot logo with loading

### ISSUE THREAD

**Issue by Shakibuzzaman3104** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#15]
I am using **T450s** _i5 5300u_. So, I followed your guide to create a bootable USB using a mac device. I mounted the EFI partition and Copied your EFI folder to the EFI drive. I have waited for almost 30mins and nothing happened. I also re-attempted the process but no luck.

**Steps to reproduce the behavior:**
I have only followed  [this](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#setting-up-the-installer) link to mount the EFI partition.

**image:**
https://imgur.com/p8769qD

**Comment by racka98** [comment]
> 
> **image:**
> https://imgur.com/p8769qD
> 

Please turn on verbose mode in Config.plist by adding -v in boot-args then send the picture when it is stuck

**Comment by Shakibuzzaman3104** [comment]
> > **image:**
> > https://imgur.com/p8769qD
> 
> Please turn on verbose mode in Config.plist by adding -v in boot-args then send the picture when it is stuck

-v is already added there but nothing is showing. 
`keepsyms=1 alcdelay=1000 -v`

**Comment by Shakibuzzaman3104** [comment]
> > > **image:**
> > > https://imgur.com/p8769qD
> > 
> > 
> > Please turn on verbose mode in Config.plist by adding -v in boot-args then send the picture when it is stuck
> 
> > -v is already added there but nothing is showing.
> > `keepsyms=1 alcdelay=1000 -v`  or should I add it like this `boot-args -v`. I tried both but no log is showing up.
> 
> Hhmm that's very odd. Is it the latest release of my EFI? Because i tested it on my USB and it worked and showed the logs and went into the installer. Use the source code zip file in the release page. If the latest one doesn't boot try the older one.
> Please see my [Config.plist](https://drive.google.com/file/d/18WAzNpa4RfVY29h6_fBNxfpMnO3SvvNc/view?usp=sharing)

I managed to show logs. Here is a snippet of the log. This shows for about 30 secs then a lot of logs that are too quick to catch and then moves on to boot logo and freezes.
[log](https://imgur.com/undefined)

**Comment by Shakibuzzaman3104** [comment]
I have tried to install catalina today and got this [error](http://imgur.com/gallery/s3L4JjM). Hope this gives you a clue on what's going on.

**Comment by racka98** [comment]
> I have tried to install catalina today and got this [error](http://imgur.com/gallery/s3L4JjM). Hope this gives you a clue on what's going on. 

I think i know the issue. I switched to OpenHFSPlus.efi in this release instead of thr regular HFSPlus.efi. Let me revert to the old HFSPlus.efi and you can test if it works

**Comment by racka98** [comment]
Ok i think I've fixed it. It boots the Catalina installer now (haven't put Big Sur in my USB yet but it should work). I'll push it and you can test if it works

**Comment by Admiral124** [comment]
Hello, I seem to be having the same issue with Big Sur. It stops at the exact same place as the OP in his original post. I have tried replacing the EFI folder with the updated files you pushed, but it still gets stuck in the same spot.

**Comment by racka98** [comment]
> Hello, I seem to be having the same issue with Big Sur. It stops at the exact same place as the OP in his original post. I have tried replacing the EFI folder with the updated files you pushed, but it still gets stuck in the same spot.

Try the one i pushed just now. There's something wrong but i can't find it. Weirdly the installer boot on my laptop

**Comment by Admiral124** [comment]
Unfortunately still the same issue. I don't have a lot of experience with MacOS, but is there a way to force a verbose load screen instead of the graphical loading bar? The verbose flag is set in the boot args just like the OP had it, but I'm assuming that's only for the OpenCore and/or XNU.

**Comment by racka98** [comment]
> Unfortunately still the same issue. I don't have a lot of experience with MacOS, but is there a way to force a verbose load screen instead of the graphical loading bar? The verbose flag is set in the boot args just like the OP had it, but I'm assuming that's only for the OpenCore and/or XNU.

The -v flag should enable verbose screen and disable the loading bar. 

It's hard for me to fix this considering it doesn't happen on my laptop. I'll look into it tomorrow.

In the meantime try this EFI i was testing with someone else who has the same problem: https://t.co/59sF1TNaeD

And use this config.plist: https://t.co/PSoYfg1NnD

You can try disabling DevirtualiseMmio quirk in Booter of Config.plist

**Comment by Admiral124** [comment]
Again, the same result. I may try just remaking the USB installer to see if that changes anything. I'm not sure if it can help at all, but [here is the final frame](https://imgur.com/y5mDrYH) before it jumps to the Apple loading bar and gets stuck.

**Comment by racka98** [comment]
> Again, the same result. I may try just remaking the USB installer to see if that changes anything. I'm not sure if it can help at all, but [here is the final frame](https://imgur.com/y5mDrYH) before it jumps to the Apple loading bar and gets stuck. 

Your problem is not the same as OP's. Yours gets past the first boot sequence but OP's kernel panics earlier.

Does it show any text when it's stuck on the Apple logo?

**Comment by Admiral124** [comment]
> > Again, the same result. I may try just remaking the USB installer to see if that changes anything. I'm not sure if it can help at all, but [here is the final frame](https://imgur.com/y5mDrYH) before it jumps to the Apple loading bar and gets stuck.
> 
> Your problem is not the same as OP's. Yours gets past the first boot sequence but OP's kernel panics earlier.
> 
> Does it show any text when it's stuck on the Apple logo?

Ahh, apologies for that.
No, there is no text. However there is a mouse cursor that you can move around but the bar never progresses any further. I've left it there for about an hour just in case.

**Comment by racka98** [comment]
> > > Again, the same result. I may try just remaking the USB installer to see if that changes anything. I'm not sure if it can help at all, but [here is the final frame](https://imgur.com/y5mDrYH) before it jumps to the Apple loading bar and gets stuck.
> > 
> > Your problem is not the same as OP's. Yours gets past the first boot sequence but OP's kernel panics earlier.
> > 
> > Does it show any text when it's stuck on the Apple logo?
> 
> Ahh, apologies for that.
> No, there is no text. However there is a mouse cursor that you can move around but the bar never progresses any further. I've left it there for about an hour just in case.

With CSM On hat happens (Either that or garbled screen). Turn it off from BIOS and see if it makes a difference.

**Comment by Admiral124** [comment]
So with CSM disabled it still crashes at the same place it seems, but now the apple loading bar screen [looks like this](https://imgur.com/syUFSgM). Also, would you like me to create a new ticket? I didn't mean to take over the OP's issue seeing as it isn't quite the same.

**Comment by racka98** [comment]
@Admiral124 turn CSM back On and open a new issue so we look into it

**Comment by Shakibuzzaman3104** [comment]
> > Unfortunately still the same issue. I don't have a lot of experience with MacOS, but is there a way to force a verbose load screen instead of the graphical loading bar? The verbose flag is set in the boot args just like the OP had it, but I'm assuming that's only for the OpenCore and/or XNU.
> 
> The -v flag should enable verbose screen and disable the loading bar.
> 
> It's hard for me to fix this considering it doesn't happen on my laptop. I'll look into it tomorrow.
> 
> In the meantime try this EFI i was testing with someone else who has the same problem: https://t.co/59sF1TNaeD
> 
> And use this config.plist: https://t.co/PSoYfg1NnD
> 
> You can try disabling DevirtualiseMmio quirk in Booter of Config.plist

Finally this worked **(for Catalina)**. But, Wifi is not working and Without pendrive I can't goto MacOS. I guess these can solved easily. 
**BTW: Your latest update didn't work.**
Thank you for the help. I don't know if it will work for Big Sur or not. So, Should I close the issue ??

**Comment by racka98** [comment]
Did you use the efi as it is or did you edit the config.plist as i mentioned. I need to know which one properly works. Send tbe config.plis which is working right now.

> But, Wifi is not working and Without pendrive I can't goto MacOS.

You can easily fix this by replacing the Airportitlwm.kext in the efi with one for Catalina which is in Intel WiFi kexts folder of this repo.


If it worked with Catalina it should work with Big Sur.

Don't close the issue yet. I need to know if it will work with Big Sur. Can you please test it with Big Sur and report. I'll have to take down the EFI in this repo and replace it with a working one. Something might have been messed up but i can't find it

**Comment by Shakibuzzaman3104** [comment]
> Did you use the efi as it is or did you edit the config.plist as i mentioned. I need to know which one properly works. Send tbe config.plis which is working right now.
I used the EFI from [this](https://t.co/59sF1TNaeD) and Config.plist from [this](https://t.co/PSoYfg1NnD) without any modification.

> Don't close the issue yet. I need to know if it will work with Big Sur. Can you please test it with Big Sur and report. I'll have to take down the EFI in this repo and replace it with a working one. Something might have been messed up but i can't find it
I am at my office right now. I will try when I get back home and let you know.

**Comment by Shakibuzzaman3104** [comment]
> > Did you use the efi as it is or did you edit the config.plist as i mentioned. I need to know which one properly works. Send tbe config.plis which is working right now.
> 
> I used the EFI from [this](https://t.co/59sF1TNaeD) and Config.plist from [this](https://t.co/PSoYfg1NnD) without any modification.
> 
> > Don't close the issue yet. I need to know if it will work with Big Sur. Can you please test it with Big Sur and report. I'll have to take down the EFI in this repo and replace it with a working one. Something might have been messed up but i can't find it
> 
> I am at my office right now. I will try when I get back home and let you know.

Ok, I have installed Big Sur without any issue using EFI from [this](https://t.co/59sF1TNaeD) and Config.plist from [this](https://t.co/PSoYfg1NnD)

**Comment by racka98** [comment]
Ok. Thanks for testing. Remember to fill in Serial number and other related stuff or your Apple ID may be kicked out very often

**Comment by Shakibuzzaman3104** [comment]
Hey Racka, I am constantly getting Hissing sound while using headphones without any audio. I tried alc_fix but no luck. Could you please give an insight into this?

**Comment by racka98** [comment]
> Hey Racka, I am constantly getting Hissing sound while using headphones without any audio. I tried alc_fix but no luck. Could you please give an insight into this?
> 
> For reference: https://www.youtube.com/watch?v=jyEvkhgJcDk

Never found a way to completely fix that. It seems like alc_fix doesn't kick in on the first boot. Putting the computer to sleep and waking it after first boot seems to fix the issue. It's a known issue with our codec

**Comment by Shakibuzzaman3104** [comment]
> 
> Never found a way to completely fix that. It seems like alc_fix doesn't kick in on the first boot. Putting the computer to sleep and waking it after first boot seems to fix the issue. It's a known issue with our codec

Thank you for the info. Hoping for a solid fix in the future. I will also be looking around.
